# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d679ed069dfcff91479244080d6842228a032b22cecbf3120e2447b7898eaa3bb29e3945908e8a2d4c856ebf81a1b1cc72f8c178e8df9f9da7f89533a0cc6d5

test:
  secret_key_base: 5f8672d3b74da3a08f1903082acb24f7ce12b7766c8550fe5cf4b12fbc166f4ce86c378573fab237f911af5fae273b397c09f194ab4f5a5fdaf1302ddddb8b89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
